language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
dist: trusty
sudo: false

notifications:
  email: false

env:
  global:
    - LOCAL_DOMAIN=cb6e6126.ngrok.io
    - LOCAL_HTTPS=true
    - RAILS_ENV=test
    - CXX=g++-4.8
addons:
  postgresql: 9.4
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - trusty-media
    packages:
    - g++-4.8
    - ffmpeg

rvm:
  - 2.3.4
  - 2.4.1

services:
  - redis-server

bundler_args: --without development production --retry=3 --jobs=3

install:
  - nvm install
  - npm install -g yarn
  - bundle install
  - yarn install

before_script:
  - bundle exec rails db:create db:migrate

script:
  - bundle exec rspec
  - npm test
  - i18n-tasks unused
